### ISSUE TITLE
Event: (no event selected) Issue using woocommerce

### ISSUE THREAD

**Issue by JLawren** [quadshot/opentickets-community#3]
Hi, I recently try this OpenTickets for my friend requirement.
but I found out that each time the user buy via product page, then the order is delivered. I notice that there is a label "Event: (no event selected)" on order list, this makes completed order has no tickets link

I am not using 'reserve' button on qtop link, perhaps you can help me why this is happened?
because for now I can do workaround by select the event manually on the order, but if I had 800 tickets, it will burn some huge effort and time, is there any solution?

www.buddhistreborn.org

**Comment by loushou** [comment]
Hey there,

It seems to me that the problem you are encountering is largely due to the approach you are taking to add the item to your cart. The ticket items should be added to your cart via the 'event' page, not the 'product' page. In fact, for many versions now, the 'product' page for all ticket products have been force to be hidden from the frontend of the site. An end user literally cannot even view a 'ticket product' page unless they are a logged in user who can edit the ticket product. Your best bet will be to funnel users to your 'calendar' page (created upon opentickets installation). From there, users will select an upcoming event. Once selected, they will be transported to the event page for that event, where an interface exists that allows them to specify how many tickets they wish to purchase, eliminating the great effort you describe for purchasing 800 tickets.

Hopefully this clears things up, and sorry for the majorly late response,
Loushou

**Comment by JLawren** [comment]
Hi,

Thankyou for the response, though I already forced to use anothe plugin for
ticketing system.

From your suggestion about 'no product page' i think its great downfall
since the way it looks is much much better on product page instead on event
page/blog pages/ calendar

Is there any work around? Like opentickets widget? Because I think the
interface is playing great part in ticket selling. Thank you.

**Comment by loushou** [comment]
Hey @JLawren,

There is currently not a work around, at least not an easy one; however, one of our upcoming extensions (the next one in fact) will be incorporating the ticket purchasing into the shop pages, as well as providing several useful widgets and shortcodes. Various users of the software have asked for this type of feature, which has previously never existed, even in our enterprise version, due to complications in how WooCommerce handles it's shop page. There have however, been recent changes to WooCommerce that actually make this possible now, so we are working on a solution for it. I will update you when it is completed, in case we have a chance to win you back. Even if we are past that, maybe it will help others at the very least.

Loushou

**Comment by JLawren** [comment]
@Loushou ,

That would be an splendid update!
I will await your updates, since there is not much offer complete features
like opentickets, expecially on so-called 'beloved' woocomerce.. hahahaa...
thank you again for your response, have a nice day!
